name: learn-github-actions
run-name: ${{ github.actor }} is testing lint
on:
  pull_request:
    branches:
      - 'main'
jobs:
  validate-lint:
    runs-on: [self-hosted,only-main-branch]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14.19.0'
    
      - run: cd ./backend
      - run: npm i
      - run: pwd
      - run: ls
      - run: npm run lint
      - run: cd ../frontend
      - run: npm i
      - run: pwd
      - run: ls
      - run: npm run lint